require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/mentors', type: :request do
  before(:each) do
    load 'db/seeds.rb'
    @admin_user = User.first
    @normal_user = User.second
  end
  # This should return the minimal set of attributes required to create a valid
  # Mentor. As you add validations to Mentor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      name: 'Omid',
      photo: 'https://image.jpg',
      bio: 'Developer'
    }
  end

  let(:invalid_attributes) do
    {
      photo: 'https://image.jpg',
      bio: 'Developer'
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # MentorsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {
      Authorization: "Bearer #{@admin_user.generate_jwt}"
    }
  end

  let(:normal_user_headers) { { Authorization: "Bearer #{@normal_user.generate_jwt}" } }

  describe 'GET /index' do
    it 'renders a successful response with list of mentors' do
      get mentors_url, headers: valid_headers
      expect(response.body).to include 'Mostafa'
      expect(response.body).to include 'Awais'
      expect(response.body).to include 'Ammar'
    end
  end

  describe 'GET /show' do
    it 'renders a successful response with a relevant resource' do
      mentor = Mentor.last
      get mentor_url(mentor)
      expect(response).to be_successful
      expect(response.body).to include mentor.name
    end

    it 'gives 404 error for non-existing mentor' do
      id = Mentor.last.id + 10
      get mentor_url(id)
      expect(response).to have_http_status(:not_found)
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Mentor' do
        expect do
          post mentors_url,
               params: { mentor: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Mentor, :count).by(1)
      end

      it 'renders a JSON response with the new mentor' do
        post mentors_url,
             params: { mentor: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Mentor' do
        expect do
          post mentors_url,
               params: { mentor: invalid_attributes }, as: :json
        end.to change(Mentor, :count).by(0)
      end

      it 'renders a JSON response with errors for the new mentor' do
        post mentors_url,
             params: { mentor: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with normal user' do
      it 'renders a JSON response with errors for the new mentor' do
        post mentors_url,
             params: { mentor: valid_attributes }, headers: normal_user_headers, as: :json
        expect(response).to have_http_status(:unauthorized)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'without authentication' do
      it 'renders a JSON response with errors for the new mentor' do
        post mentors_url,
             params: { mentor: valid_attributes }, as: :json
        expect(response).to have_http_status(:unauthorized)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested mentor' do
      valid_attributes[:user] = @admin_user
      mentor = Mentor.create! valid_attributes
      expect do
        delete mentor_url(mentor), headers: valid_headers, as: :json
      end.to change(Mentor, :count).by(-1)
    end

    it 'gives 404 on attempt for deleting non-existing mentor' do
      delete mentor_url(Mentor.last.id + 1), headers: valid_headers, as: :json
      expect(response).to have_http_status(:not_found)
    end

    it 'gives error if user is not authorized' do
      delete mentor_url(1)
      expect(response).to have_http_status(:unauthorized)
    end
  end
end
